server.port: 5656
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/recipes
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  liquibase:
    drop-first: true
    contexts: local

logging:
  level:
    ROOT: INFO
    pmb.recipes: DEBUG
